project:
  type: website
  output-dir: _site

quartodoc:
  package: dsci_524_group23
  sections:
    - title: Functions
      desc: API Reference
      contents:
        - standardize_schema
        - find_duplicates
        - handle_missing
        - missing_summary

website:
  title: "dsci_524_group23"
  navbar:
    left:
      - text: "Reference"
        href: reference/index.qmd
